name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  GEODE_SDK: ${{ github.workspace }}/sdk
  GEODE_VERSION: nightly
  CLI_VERSION: v2.0.0
  MOD_NAME: nongd
  MOD_ID: fleym.nongd


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          
          - name: macOS
            os: macos-latest
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: geode-sdk/build-geode-mod@combine
        id: build
      
      - uses: actions/upload-artifact@v3
        with:
          name: Build Output
          path: ${{steps.build.outputs.build-output}}
